__author__ = 'Lorenzo Argentieri'

diffuse = 'Diffuse'
backlight = 'Backlight'
specularColor = 'Specular'
specularWeight = 'specularWeight'
specularRoughness = 'Roughness'
fresnel = 'f0'
normal = 'Normal'
height = 'Height'
metallic = 'Metallic'
emission = 'Emissive'
