"""This module contains a function to generate a unique name based on a given name.

The function nameCheck takes a name as input and returns a new name that is not
already in use in the current scene. The new name is generated by appending a
numeric suffix to the original name.

For example, if the input name is 'myObject', the function may return
'myObject1', 'myObject2', etc. depending on the number of objects in the scene
with the same name.

The function uses the pymel.core.ls function to get a list of objects in the
scene with the given name, and then appends the length of this list plus one to
the original name to generate a new name.
"""

__author__ = 'Lorenzo Argentieri'

import pymel.core as pm


def nameCheck(name):
    """Return a new univocal name based on the given name.

    Args:
        name: str, the name to use as a base for the new name.

    Returns:
        str, a new name that is not already in use in the current scene.
    """
    nameList = pm.ls(name)
    nameCount = len(nameList)

    newNameRPart = str(name).rpartition('_')
    newName = newNameRPart[0].replace('*', '') + str(nameCount + 1) + newNameRPart[1] + newNameRPart[2]
    return newName